dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js

cache:
  directories:
     - ./node_modules

stages:
  - build
  - test
  - name: optional
    if: (NOT type IN (pull_request)) AND (branch = master)
  - deploy

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    - env: ng2
    - node_js: "7"
    - node_js: "8"
  include:
    # Build stage
    - stage: build
      script: npm run lint
      env: lint
    - script: npm run build
      env: build

    # Test stage
    - stage: test
      script: npm run test
      env: test
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=0 --nosilent
      env: e2e-0
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=1 --nosilent
      env: e2e-1
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=2 --nosilent
      env: e2e-2
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nb-shards=4 --shard=3 --nosilent
      env: e2e-3
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --eject "--glob=tests/build/**"
      env: eject

    # Optional stage.
    - stage: optional
      node_js: "6"
      os: linux
      script: node tests/run_e2e.js --ng2 "--glob=tests/build/**"
      env: ng2
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --ng4 "--glob=tests/build/**"
      env: ng4
    - node_js: "6"
      os: linux
      script: node tests/run_e2e.js --nightly "--glob=tests/build/**"
      env: nightly
    - node_js: "7"
      os: linux
      script: node tests/run_e2e.js "--glob=tests/build/**"
      env: node7
    - node_js: "8"
      os: linux
      script: node tests/run_e2e.js "--glob=tests/build/**"
      env: node8

    # Deploy stage
    - stage: deploy
      script: skip
      env: builds
      deploy:
      - provider: script
        script: node scripts/git-builds.js
        skip_cleanup: true
        on:
          all_branches: true
    - script: skip
      env: publish
      deploy:
      - provider: script
        script: node scripts/publish/publish.js
        skip_cleanup: true
        on:
          tags: true


before_install:
  # Install npm 5.
  - npm install -g npm@~5.3.0

install:
  - npm install
